version: "3"
services:
  db_dev:
    image: postgres:12.3-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: colorpixels
      POSTGRES_PASSWORD: colorpixelspass
    volumes:
      - db-data:/var/lib/postgresql/data

  db_test:
    image: postgres:12.3-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: colorpixels
      POSTGRES_PASSWORD: colorpixelspass


volumes:
  db-data: